name: prod.yml
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Login docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/books:latest .
      - name: Push to Docker Hub Container Registry
        run: |
          docker tag ${{secrets.DOCKER_USERNAME}}/books:latest ${{secrets.DOCKER_USERNAME}}/books:${{github.run_id}}
          
          docker push ${{secrets.DOCKER_USERNAME}}/books:${{github.run_id}}
          docker push ${{secrets.DOCKER_USERNAME}}/books:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull ${{secrets.DOCKER_USERNAME}}/books:latest
      - name: Remove docker container
        run: docker rm -f books
      - name: Run docker container
        run: docker run -d -p 8080:8080 -e DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}} -e DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}} -e DATABASE_HOST=${{secrets.DATABASE_HOST}} -e DATABASE_PORT=${{secrets.DATABASE_PORT}} -e DATABASE_DB_NAME=${{secrets.DATABASE_DB_NAME}} --name books --network app_with_db ${{secrets.DOCKER_USERNAME}}/books:latest